### ISSUE TITLE
illusioners underground perpetuate raids

### ISSUE THREAD

**Issue by Theiromia** [team-abnormals/savage-and-ravage#117]
I went on to start a level 6 raid, I go over to where the raid started. I kill all of them, but the raid bar is still up, I check around the area for caves, and I found them and killed the illagers there, but the raid bar hadn't changed much. then i wonder "illusioners spawn naturally, would they add to the raid?", and when I went on a mad manhunt underground and i can never kill all of them (and they did take away from the raid bar when i killed them)

**Comment by bageldotjpg** [comment]
This mod doesn't make illusioners spawn, and also this is a vanilla mechanic
