### ISSUE TITLE
[Enhancement] Allow humanoid mobs to wear Griefer Armour

### ISSUE THREAD

**Issue by nekomaster1000** [team-abnormals/savage-and-ravage#118]
Hi there! 
I'm developing a modpack that utilises **Mobs Properties Randomness,** and creating 'soldier' mobs that spawn fully clad in armour. (The mobs in question being Zombies, Skeletons and Piglins.) I've tried adding Griefer Armour-utilising soldiers, too, but it seems they can't wear it. 
Would it be possible for them to be capable of wearing the armour in the future be added, or is this not feasible? 
Would be highly appreciated if it was added. 
Thanks!

**Comment by bageldotjpg** [comment]
They definitely can, Piglins even have a custom helmet model for it!
I would make sure you're using the correct item ID.
