### ISSUE TITLE
Release new Curseforge version

### ISSUE THREAD

**Issue by kyragit** [team-abnormals/savage-and-ravage#134]
There have been multiple important fixes pushed to the repo, but there hasn't been a new Curse version since August. Specifically, issue #119 isn't fixed in the release version and I've had to use a compiled jar from github for testing my pack. I'd appreciate it a lot if these patches were on the release version!

**Comment by bageldotjpg** [comment]
https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage/files/4396966

**Comment by kyragit** [comment]
Awesome!
