### ISSUE TITLE
[1.19.2] Raid farm broken

### ISSUE THREAD

**Issue by PrincedelaLune** [team-abnormals/savage-and-ravage#147]
I built a Vanilla raid farm in a modded world with S&R and the raid do not happens properly.
This is the farm that I built : https://youtu.be/n3mOlrMGjUg
I believe the raid stops when "shifted up" because the player is too far away from the raid's center.
If this is a feature, could this be configurable ?
Tested in 1.19.2:
forge - 43.2.7
BluePrint - 6.1.2
Savage & Ravage - 5.0.4

**Comment by bageldotjpg** [comment]
Probably due to the banner burning changes which you can disable in config
