### ISSUE TITLE
(1.20.1) Crossbows dont use the mischief arrow and spectral arrow textures

### ISSUE THREAD

**Issue by ficonazo** [team-abnormals/savage-and-ravage#163]
I saw the mod had textures of crossbows loaded with arrow of mischief and the golden arrows, but when i use crossbows with them it doesnt seem to be loaded with their textures?

https://github.com/team-abnormals/savage-and-ravage/assets/132626453/80f7edcf-a3ce-4d8f-9b30-098bfbd317e9

Mod Version: 6.0.0
Blueprint version: 7.1.0
Minecraft version 1.20.1
forge version 47.2.21

https://github.com/team-abnormals/savage-and-ravage/assets/132626453/826854a6-f7c5-4bad-ad4a-52f378258b82

**Comment by bageldotjpg** [comment]
Yeah it would require replacing the crossbow model which we aren't gonna do, the textures are just unused
