### ISSUE TITLE
Where is 1.20.1?

### ISSUE THREAD

**Issue by SebSemos** [team-abnormals/savage-and-ravage#167]
Am I stupid? :p Both Modrinth and Curse stop at 1.19.2, but the issue have several 1.20 stuff?

**Comment by NixityNull** [comment]
It's currently only available to patreon members for playtesting. They'll make it public when it's completed, but until then if you want it or any of the other beta versions of mods that are currently 1.19.2, you're going to wanna become a patron or try compiling the files from here.
