### ISSUE TITLE
Iceologer Ice  Block is Untextured

### ISSUE THREAD

**Issue by CROOT-ROM** [team-abnormals/savage-and-ravage#47]
As the above says, latest Version of savage and Ravage, Using these mods. 
![image](https://user-images.githubusercontent.com/68515101/101272201-41bc5780-3747-11eb-9208-519e308a78c2.png)
Image of Bug in Game:
https://imgur.com/a/eKyVaBw

**Comment by bageldotjpg** [comment]
uninstall optifine, or try and see if optiforge fixes it
