### ISSUE TITLE
[SUGGESTION] The Smithy & The Illager Baron

### ISSUE THREAD

**Issue by UnexpectedProton** [team-abnormals/savage-and-ravage#49]
The Smithy:
The Smithy would be a new castle-like structure that would spawn in mountain biomes. It would be composed of stone bricks and spruce wood. The purpose of the smithy would be to forge the Illagers weapons, as well as being a prison for captured villagers. Several ravagers would be in pens outside, and a villager would be hanging in a cage.

The Illager Baron:
The Baron is the leader of the Smithy. He would spawn in the treasure room of the castle. His fight would involve summoning powerful Gloomstone Golems, which would summon runes. He could also summon green shooting skulls that would circle around him. Other boss fight details are up to you, of course.

Illager Crown and Tablet: 
The Baron would either drop the Illager Crown, which would allow you to be peaceful with most hostile mobs as long as you were also with a group of illagers, or the Illager Tablet. The Tablet summons the orbiting green shooting skulls from the boss fight. By shift-right clicking, you can change the mode to summon a Gloomstone Golem. It would have durability, although mending and unbreaking could be used.

If Quark is installed, the Baron would also drop a random ancient tome.

**Comment by bageldotjpg** [comment]
Please direct suggestions to our discord community
