### ISSUE TITLE
Illager outpost spawning on ice sheet over water

### ISSUE THREAD

**Issue by turabian-luvr** [team-abnormals/savage-and-ravage#53]
![2021-01-02_17 39 38](https://user-images.githubusercontent.com/54744184/103470376-43be0a00-4d37-11eb-97b5-f36135b5fedd.png)

As shown in the screenshot. Latest version of S & R installed on 1.16.4 with Terraforged and BoP.

**Comment by abigailfails** [comment]
This isn't S&R's fault, all it does is replace the existing watchtower with a different one.

**Comment by abigailfails** [comment]
I have a feeling this might be a vanilla bug - after all it created nice grassy terrain to put it on, but you could try asking Terraforged and BoP about it.
