### ISSUE TITLE
[1.16.5-3.1.0][Suggestion] Set Pillagers and other mobs to be persistent when spawned at first structure generation

### ISSUE THREAD

**Issue by TelepathicGrunt** [team-abnormals/savage-and-ravage#66]
Usually when mobs are spawned by Jigsaw blocks or by structure's first generation, their persistence is set to true so that the mob will not despawn over time. Since the Savage and Ravage Outposts has a ton of pillagers spawned by jigsaw block and Skeleton Villagers spawned in zombie villages, these mobs should have their persistence set to true.

It might be why this person could not find any pillagers when using a datapack that makes Repurposed Structures's outpost uses Savage and Ravage's jigsaw block for mob spawning. It seems the Pillagers might had despawned before the person fully made their way to the outpost if they are using the latest version of Savage and Ravage (And yes, pillagers spawn over time in my outposts as well but it seems it wasn't quick enough): https://github.com/TelepathicGrunt/RepurposedStructures/issues/76

Images of what I mean:
![image](https://user-images.githubusercontent.com/40846040/113571282-173eb600-95e4-11eb-80c5-c7761215afbe.png)
![image](https://user-images.githubusercontent.com/40846040/113571739-e7dc7900-95e4-11eb-90e7-8c632df6664a.png)

Hopefully this helps!

**Comment by abigailfails** [comment]
Thanks for telling me, I just fixed it in 76c00ea.
