### ISSUE TITLE
Some parts of the Pillager Outpost structure don't use Dark Oak Chests if Quark is installed

### ISSUE THREAD

**Issue by Brun333rp** [team-abnormals/savage-and-ravage#67]

**Comment by TelepathicGrunt** [comment]
@Brun333rp What version of Savage and Ravage are you using? Latest version seems to work for me.

Also, are you using Repurposed Structures with a Savage and Ravage compat datapack for it?

**Comment by Brun333rp** [comment]
not related with Repurposed Structures at all

**Comment by abigailfails** [comment]
...but what version were you using?

**Comment by Brun333rp** [comment]
I don't remember, it's been a while since I opened this issue. and I didn't played Minecraft too much lately, so I don't know if this issue is still happening
