### ISSUE TITLE
Config not applying when Halogen is installed

### ISSUE THREAD

**Issue by StrangerSon71** [team-abnormals/savage-and-ravage#73]
A Creeper explosion destroyed blocks without spawning creepies

Config:[entities]

	[entities.creepers]
		"Creepers drop Creeper Spores after they die from an explosion" = true
		"Creepie explosions destroy blocks" = true
		"Creeper explosions spawn creepies" = true
		"Creeper explosions destroy blocks" = false

	[entities.illagers]
		#Illagers with banners will no longer give Bad Omen when you kill them
		#Instead, you will have to place and burn the banner that they drop with flint and steel or a fire charge
		"Illagers no longer give Bad Omen when killed" = true

**Comment by abigailfails** [comment]
Did you completely restart the game first?

**Comment by StrangerSon71** [comment]
Yes, a persistent problem despite being on the latest version.

**Comment by StrangerSon71** [comment]
Please fix this on the 1.16.5 version and not just 1.17.1, I feel like this is a rather high priority bug.

**Comment by abigailfails** [comment]
I can't reprdouce this on the latest person. Can you post the `latest.log` and `debug.log` files after a creeper explodes in a world?

**Comment by StrangerSon71** [comment]
Yes, once I am not busy.

**Comment by StrangerSon71** [comment]
Here is a segment of the latest.log that had a creeper explosion:
https://pastebin.com/BViAJNUB

**Comment by StrangerSon71** [comment]
I can't reproduce this individually either, it's probably a compatibility issue.

**Comment by StrangerSon71** [comment]
I can't show the debug.log do to character limits on both github and pastebin.

**Comment by abigailfails** [comment]
> 
> 
> Here is a segment of the latest.log that had a creeper explosion:
> https://pastebin.com/BViAJNUB

There's nothing referring to creepers here. Could you try leaving the world right after a creeper explodes and then copying the last 200 lines or so?

**Comment by abigailfails** [comment]
Also, considering this is a compatability issue, could you list what mods you were using when this happened?

**Comment by StrangerSon71** [comment]
That’s pretty much what I did, I might be able to try again better.

**Comment by StrangerSon71** [comment]
Modlist is that of Strangely Modded modpack, either I can list that here or you can check the relations on CurseForge

**Comment by abigailfails** [comment]
i'll check on cf

**Comment by abigailfails** [comment]
> 
> 
> That’s pretty much what I did, I might be able to try again better.

Ah, in that case it's probably not an error, but another mod returning the explosion event. I guess i'll just look through the list to find it 😅

**Comment by StrangerSon71** [comment]
Did you find it?

**Comment by StrangerSon71** [comment]
Did you find it?

**Comment by Pedroescamoso** [comment]
I found a sodium reforge or halogen bug (Did they change the name?) bug with the savage and ravage mod which makes the creppers destroy blocks setting not applied

**Comment by StrangerSon71** [comment]
They did change the name, and thank you for isolating the bug!

**Comment by abigailfails** [comment]
Looks like there was [already an issue](https://github.com/spoorn/sodium-forge/issues/21) on the Halogen github. They closed it by disabling Lithium's mixins by default, so i guess Strangely Modded enabled that.

**Comment by StrangerSon71** [comment]
Actually, I think it just downloaded the mod before it was disabled by default, guess I can just disable it for the next update.
