### ISSUE TITLE
Ice chunks most of the times don't hit entities.

### ISSUE THREAD

**Issue by Insane96** [team-abnormals/savage-and-ravage#77]
It's due to begin a projectile (so only the mob's hitbox is taken into account) and not the full chunk hitbox.

As seen here: 
https://discord.com/channels/650003402218274816/689895188058865788/868209612715884554

**Comment by abigailfails** [comment]
This was fixed in ec90bb94dc3c13ea951859b5e2274dbb496c06b0, so it'll be out in the next update.
