### ISSUE TITLE
Gloomy Tile Double Slab & Double Vertical Slab blocks only drop one slab when broken

### ISSUE THREAD

**Issue by aurora-hope** [team-abnormals/savage-and-ravage#78]
mod version: 3.1.0 (latest at time of writing)
instance: valhelsia 3, nearly unmodified (only changed one config, s&r's, to disable creeper griefing)
steps to reproduce: place two gloomy tile slabs (horizontal or vertical) in the same block and then break it

**Comment by abigailfails** [comment]
Fixed cb4857b
