### ISSUE TITLE
Help,

### ISSUE THREAD

**Issue by Pedroescamoso** [team-abnormals/savage-and-ravage#83]
excuse me then the solution is to activate the lithium in the sodium configuration? (Since I did it and I stay the same)

**Comment by abigailfails** [comment]
deactivate

**Comment by Pedroescamoso** [comment]
By default it is deactivated and the problem with creppers still continues, do you have to wait for the next update of the mod?

**Comment by abigailfails** [comment]
There's nothing I can do about it then, you'll have to reopen the issue in Halogen's github
