### ISSUE TITLE
Mischief arrow causing insane mob spawns

### ISSUE THREAD

**Issue by SuperiorGhoul42** [team-abnormals/savage-and-ravage#90]
By making a setup similar to this, it is possible to spawn unlimited 'creepies' with the mischief arrow, as it spawns one every time it bounces of an entity that can't be hurt by projectiles, but still interacts with them(e.g. the mannequin from the [mannequins](https://www.curseforge.com/minecraft/mc-mods/mannequins) mod, a player in creative, enderman with no teleport options etc...), which could lead to server griefing, involving crashing, and possibly could be done accidentally on an ssp world(I did by trying to test bow/mischief arrow damage on the mannequin).

![image](https://user-images.githubusercontent.com/48633893/139723847-8f9f8b46-9fd7-4997-b458-870eb2bcadf3.png)

**Comment by abigailfails** [comment]
lol this is really funny, thanks for reporting
